export const ProjectTopics = [
  {
    key: 1,
    name: "Certification",
    id: "certificate",
    hasSubTopics: false,
  },
  {
    key: 2,
    name: "Declaration",
    id: "declaration",
    hasSubTopics: false,
  },
  {
    key: 3,
    name: "Acknowledgement",
    id: "acknowledgement",
    hasSubTopics: false,
  },
  {
    key: 4,
    name: "Table of contents",
    id: "table-of-contents",
    hasSubTopics: true,
    subTopics: [
      {
        key: 1,
        name: "Abstract",
        id: "abstract",
        hasSubTopics: false,
      },
      {
        key: 2,
        name: "Introduction",
        id: "introduction",
        hasSubTopics: false,
      },
      {
        key: 3,
        name: "Traffic Lights - Traffic signal control system",
        id: "traffic-lights",
        hasSubTopics: false,
      },
      {
        key: 4,
        name: "Automatic Distance Recognition",
        id: "automatic-distance-recognition",
        hasSubTopics: false,
      },
      {
        key: 4,
        name: "Smart Parking",
        id: "smart-parking",
        hasSubTopics: false,
      },
      {
        key: 5,
        name: "Law Enforcement in Traffic using AI",
        id: "law-enfourcement",
        hasSubTopics: false,
      },
      {
        key: 6,
        name: "What is ITS? Intelligent Traffic Management System",
        id: "itms",
        hasSubTopics: false,
      },
      {
        key: 7,
        name: "What are the Benefits of using AI in traffic management?",
        id: "benefits-aitm",
        hasSubTopics: false,
      },
      {
        key: 8,
        name: "Quality Data - The Key to artificial intelligence in road traffic",
        id: "quality-data",
        hasSubTopics: false,
      },
      {
        key: 9,
        name: "AI in traffic management - A controversial support",
        id: "ai-in-traffic-management",
        hasSubTopics: false,
      },
      {
        key: 10,
        name: "Challenges of using AI in traffic management",
        id: "challenges-of-using-ai-tm",
        hasSubTopics: false,
      },
      {
        key: 11,
        name: "Cyber security issues",
        id: "cyber-security-issues",
        hasSubTopics: false,
      },
      {
        key: 12,
        name: "Ethical considerations – Will AI replace us in traffic management?",
        id: "ethical-considerations",
        hasSubTopics: false,
      },
      {
        key: 13,
        name: "The Smart City – AI Traffic Systems in cities",
        id: "smart-city-ai",
        hasSubTopics: false,
      },
      {
        key: 14,
        name: "Adaptive traffic control system(ATCS) ",
        id: "adaptive-traaffic-control-system",
        hasSubTopics: false,
      },
      {
        key: 15,
        name: "Automated vehicles",
        id: "automated-vehicles",
        hasSubTopics: false,
      },
      {
        key: 16,
        name: "Intelligent parking planning",
        id: "intelligent-parking-planning",
        hasSubTopics: false,
      },
      {
        key: 17,
        name: "Reducing Traffic Congestion – Improving Road Traffic Flow",
        id: "reducing-traffic-congestion",
        hasSubTopics: false,
      },
      {
        key: 18,
        name: "Safety and Emergency Situations ",
        id: "safety-and-emergency-situations",
        hasSubTopics: false,
      },
      {
        key: 19,
        name: "Transit Planning – Intelligent Transportation Systems",
        id: "tpits",
        hasSubTopics: false,
      },
      {
        key: 20,
        name: "Urban Planning ",
        id: "up",
        hasSubTopics: false,
      },
    ],
  },
];